# Generated by Django 4.0.6 on 2022-08-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_record',
            name='batch',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('B.Tech', 'Bachelors of Technology'), ('BSc', 'Bachelors of Science'), ('BE', 'Bachelors in Engineering')], default='BE', max_length=255),
        ),
    ]
