# Generated by Django 3.2.15 on 2022-08-16 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('16', 'B.E/B.Tech in Power Engineering'), ('10', 'B.E/B.Tech in Electronics and Telecommunication Engineering'), ('1', 'B.E/B.Tech in Mechanical Engineering'), ('15', 'B.E/B.Tech in Mining Engineering'), ('6', 'B.E/B.Tech in Chemical Engineering'), ('19', 'B.E/B.Tech in Genetic Engineering'), ('12', 'B.E/B.Tech in Aeronautical Engineering'), ('27', 'B.E/B.Tech in Motorsport Engineering'), ('0', 'B.E/B.Tech in Computer Science Engineering'), ('29', 'B.E/B.Tech in Textile Engineering'), ('14', 'B.E/B.Tech in Automobile Engineering'), ('3', 'B.E/B.Tech in Electrical Engineering'), ('17', 'B.E/B.Tech in Production Engineering'), ('26', 'B.E/B.Tech in Infrastructure Engineering'), ('30', 'B.E/B.Tech in Marine Engineering'), ('33', 'B.E/B.Tech in Petrochemical Engineering'), ('35', 'B.E/B.Tech in Geotechnical Engineering'), ('28', 'B.E/B.Tech in Metallurgy Engineering'), ('23', 'B.E/B.Tech in Environmental Engineering'), ('2', 'B.E/B.Tech in Electronics and Communication Engineering'), ('8', 'B.E/B.Tech in Instrumentation and Control Engineering'), ('22', 'B.E/B.Tech in Agricultural Engineering'), ('18', 'B.E/B.Tech in Biotechnology Engineering'), ('5', 'B.E/B.Tech in Civil Engineering'), ('32', 'B.E/B.Tech in Geoinformatics'), ('9', 'B.E/B.Tech in Electronics Engineering'), ('34', 'B.E/B.Tech in Polymer Engineering'), ('13', 'B.E/B.Tech in Aerospace Engineering'), ('7', 'B.E/B.Tech in Information Technology'), ('24', 'B.E/B.Tech in Dairy Technology and Engineering'), ('31', 'B.E/B.Tech in Naval Architecture'), ('21', 'B.E/B.Tech in Food Processing and Technology'), ('36', 'B.E / B.Tech in Nuclear Engineering'), ('11', 'B.E/B.Tech in Petroleum Engineering'), ('25', 'B.E/B.Tech in Agricultural Information Technology'), ('20', 'B.E/B.Tech in Plastics Engineering'), ('4', 'B.E/B.Tech in Electrical and Electronics Engineering')], default='0', max_length=255),
        ),
        migrations.CreateModel(
            name='Semester_subject_registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits', models.FloatField(default=0)),
                ('subject', models.CharField(max_length=255)),
                ('subject_code', models.CharField(max_length=255)),
                ('semester', models.IntegerField()),
                ('graduating_year', models.IntegerField()),
                ('degree', models.CharField(choices=[('16', 'B.E/B.Tech in Power Engineering'), ('10', 'B.E/B.Tech in Electronics and Telecommunication Engineering'), ('1', 'B.E/B.Tech in Mechanical Engineering'), ('15', 'B.E/B.Tech in Mining Engineering'), ('6', 'B.E/B.Tech in Chemical Engineering'), ('19', 'B.E/B.Tech in Genetic Engineering'), ('12', 'B.E/B.Tech in Aeronautical Engineering'), ('27', 'B.E/B.Tech in Motorsport Engineering'), ('0', 'B.E/B.Tech in Computer Science Engineering'), ('29', 'B.E/B.Tech in Textile Engineering'), ('14', 'B.E/B.Tech in Automobile Engineering'), ('3', 'B.E/B.Tech in Electrical Engineering'), ('17', 'B.E/B.Tech in Production Engineering'), ('26', 'B.E/B.Tech in Infrastructure Engineering'), ('30', 'B.E/B.Tech in Marine Engineering'), ('33', 'B.E/B.Tech in Petrochemical Engineering'), ('35', 'B.E/B.Tech in Geotechnical Engineering'), ('28', 'B.E/B.Tech in Metallurgy Engineering'), ('23', 'B.E/B.Tech in Environmental Engineering'), ('2', 'B.E/B.Tech in Electronics and Communication Engineering'), ('8', 'B.E/B.Tech in Instrumentation and Control Engineering'), ('22', 'B.E/B.Tech in Agricultural Engineering'), ('18', 'B.E/B.Tech in Biotechnology Engineering'), ('5', 'B.E/B.Tech in Civil Engineering'), ('32', 'B.E/B.Tech in Geoinformatics'), ('9', 'B.E/B.Tech in Electronics Engineering'), ('34', 'B.E/B.Tech in Polymer Engineering'), ('13', 'B.E/B.Tech in Aerospace Engineering'), ('7', 'B.E/B.Tech in Information Technology'), ('24', 'B.E/B.Tech in Dairy Technology and Engineering'), ('31', 'B.E/B.Tech in Naval Architecture'), ('21', 'B.E/B.Tech in Food Processing and Technology'), ('36', 'B.E / B.Tech in Nuclear Engineering'), ('11', 'B.E/B.Tech in Petroleum Engineering'), ('25', 'B.E/B.Tech in Agricultural Information Technology'), ('20', 'B.E/B.Tech in Plastics Engineering'), ('4', 'B.E/B.Tech in Electrical and Electronics Engineering')], default='0', max_length=255)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.institute')),
            ],
        ),
    ]
