# Generated by Django 3.2.15 on 2022-08-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('BSc', 'Bachelors of Science'), ('B.Tech', 'Bachelors of Technology'), ('BE', 'Bachelors in Engineering')], default='BE', max_length=255),
        ),
    ]
