# Generated by Django 3.2.15 on 2022-08-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_student_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('B.Tech', 'Bachelors of Technology'), ('BSc', 'Bachelors of Science'), ('BE', 'Bachelors in Engineering')], default='BE', max_length=255),
        ),
    ]
