# Generated by Django 4.0.6 on 2022-08-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_academic_record_batch_alter_student_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_record',
            name='batch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('BSc', 'Bachelors of Science'), ('BE', 'Bachelors in Engineering'), ('B.Tech', 'Bachelors of Technology')], default='BE', max_length=255),
        ),
    ]
