# Generated by Django 3.2.15 on 2022-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20220819_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_subject_registration',
            name='degree',
            field=models.CharField(choices=[('20', 'B.E/B.Tech in Plastics Engineering'), ('19', 'B.E/B.Tech in Genetic Engineering'), ('26', 'B.E/B.Tech in Infrastructure Engineering'), ('6', 'B.E/B.Tech in Chemical Engineering'), ('9', 'B.E/B.Tech in Electronics Engineering'), ('21', 'B.E/B.Tech in Food Processing and Technology'), ('15', 'B.E/B.Tech in Mining Engineering'), ('28', 'B.E/B.Tech in Metallurgy Engineering'), ('11', 'B.E/B.Tech in Petroleum Engineering'), ('22', 'B.E/B.Tech in Agricultural Engineering'), ('2', 'B.E/B.Tech in Electronics and Communication Engineering'), ('13', 'B.E/B.Tech in Aerospace Engineering'), ('8', 'B.E/B.Tech in Instrumentation and Control Engineering'), ('23', 'B.E/B.Tech in Environmental Engineering'), ('7', 'B.E/B.Tech in Information Technology'), ('0', 'B.E/B.Tech in Computer Science Engineering'), ('29', 'B.E/B.Tech in Textile Engineering'), ('30', 'B.E/B.Tech in Marine Engineering'), ('36', 'B.E / B.Tech in Nuclear Engineering'), ('1', 'B.E/B.Tech in Mechanical Engineering'), ('35', 'B.E/B.Tech in Geotechnical Engineering'), ('17', 'B.E/B.Tech in Production Engineering'), ('4', 'B.E/B.Tech in Electrical and Electronics Engineering'), ('5', 'B.E/B.Tech in Civil Engineering'), ('12', 'B.E/B.Tech in Aeronautical Engineering'), ('3', 'B.E/B.Tech in Electrical Engineering'), ('16', 'B.E/B.Tech in Power Engineering'), ('24', 'B.E/B.Tech in Dairy Technology and Engineering'), ('18', 'B.E/B.Tech in Biotechnology Engineering'), ('31', 'B.E/B.Tech in Naval Architecture'), ('25', 'B.E/B.Tech in Agricultural Information Technology'), ('33', 'B.E/B.Tech in Petrochemical Engineering'), ('10', 'B.E/B.Tech in Electronics and Telecommunication Engineering'), ('34', 'B.E/B.Tech in Polymer Engineering'), ('32', 'B.E/B.Tech in Geoinformatics'), ('27', 'B.E/B.Tech in Motorsport Engineering'), ('14', 'B.E/B.Tech in Automobile Engineering')], default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('20', 'B.E/B.Tech in Plastics Engineering'), ('19', 'B.E/B.Tech in Genetic Engineering'), ('26', 'B.E/B.Tech in Infrastructure Engineering'), ('6', 'B.E/B.Tech in Chemical Engineering'), ('9', 'B.E/B.Tech in Electronics Engineering'), ('21', 'B.E/B.Tech in Food Processing and Technology'), ('15', 'B.E/B.Tech in Mining Engineering'), ('28', 'B.E/B.Tech in Metallurgy Engineering'), ('11', 'B.E/B.Tech in Petroleum Engineering'), ('22', 'B.E/B.Tech in Agricultural Engineering'), ('2', 'B.E/B.Tech in Electronics and Communication Engineering'), ('13', 'B.E/B.Tech in Aerospace Engineering'), ('8', 'B.E/B.Tech in Instrumentation and Control Engineering'), ('23', 'B.E/B.Tech in Environmental Engineering'), ('7', 'B.E/B.Tech in Information Technology'), ('0', 'B.E/B.Tech in Computer Science Engineering'), ('29', 'B.E/B.Tech in Textile Engineering'), ('30', 'B.E/B.Tech in Marine Engineering'), ('36', 'B.E / B.Tech in Nuclear Engineering'), ('1', 'B.E/B.Tech in Mechanical Engineering'), ('35', 'B.E/B.Tech in Geotechnical Engineering'), ('17', 'B.E/B.Tech in Production Engineering'), ('4', 'B.E/B.Tech in Electrical and Electronics Engineering'), ('5', 'B.E/B.Tech in Civil Engineering'), ('12', 'B.E/B.Tech in Aeronautical Engineering'), ('3', 'B.E/B.Tech in Electrical Engineering'), ('16', 'B.E/B.Tech in Power Engineering'), ('24', 'B.E/B.Tech in Dairy Technology and Engineering'), ('18', 'B.E/B.Tech in Biotechnology Engineering'), ('31', 'B.E/B.Tech in Naval Architecture'), ('25', 'B.E/B.Tech in Agricultural Information Technology'), ('33', 'B.E/B.Tech in Petrochemical Engineering'), ('10', 'B.E/B.Tech in Electronics and Telecommunication Engineering'), ('34', 'B.E/B.Tech in Polymer Engineering'), ('32', 'B.E/B.Tech in Geoinformatics'), ('27', 'B.E/B.Tech in Motorsport Engineering'), ('14', 'B.E/B.Tech in Automobile Engineering')], default='0', max_length=255),
        ),
    ]
