# Generated by Django 3.2.15 on 2022-08-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20220818_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteevent',
            name='event_description',
            field=models.TextField(default='No Information', null=True),
        ),
        migrations.AlterField(
            model_name='instituteevent',
            name='event_overview',
            field=models.CharField(default='No Information', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='semester_subject_registration',
            name='degree',
            field=models.CharField(choices=[('13', 'B.E/B.Tech in Aerospace Engineering'), ('36', 'B.E / B.Tech in Nuclear Engineering'), ('30', 'B.E/B.Tech in Marine Engineering'), ('18', 'B.E/B.Tech in Biotechnology Engineering'), ('17', 'B.E/B.Tech in Production Engineering'), ('8', 'B.E/B.Tech in Instrumentation and Control Engineering'), ('12', 'B.E/B.Tech in Aeronautical Engineering'), ('28', 'B.E/B.Tech in Metallurgy Engineering'), ('34', 'B.E/B.Tech in Polymer Engineering'), ('26', 'B.E/B.Tech in Infrastructure Engineering'), ('14', 'B.E/B.Tech in Automobile Engineering'), ('16', 'B.E/B.Tech in Power Engineering'), ('31', 'B.E/B.Tech in Naval Architecture'), ('20', 'B.E/B.Tech in Plastics Engineering'), ('1', 'B.E/B.Tech in Mechanical Engineering'), ('11', 'B.E/B.Tech in Petroleum Engineering'), ('7', 'B.E/B.Tech in Information Technology'), ('23', 'B.E/B.Tech in Environmental Engineering'), ('32', 'B.E/B.Tech in Geoinformatics'), ('15', 'B.E/B.Tech in Mining Engineering'), ('22', 'B.E/B.Tech in Agricultural Engineering'), ('21', 'B.E/B.Tech in Food Processing and Technology'), ('35', 'B.E/B.Tech in Geotechnical Engineering'), ('10', 'B.E/B.Tech in Electronics and Telecommunication Engineering'), ('4', 'B.E/B.Tech in Electrical and Electronics Engineering'), ('5', 'B.E/B.Tech in Civil Engineering'), ('2', 'B.E/B.Tech in Electronics and Communication Engineering'), ('27', 'B.E/B.Tech in Motorsport Engineering'), ('24', 'B.E/B.Tech in Dairy Technology and Engineering'), ('0', 'B.E/B.Tech in Computer Science Engineering'), ('9', 'B.E/B.Tech in Electronics Engineering'), ('19', 'B.E/B.Tech in Genetic Engineering'), ('33', 'B.E/B.Tech in Petrochemical Engineering'), ('29', 'B.E/B.Tech in Textile Engineering'), ('25', 'B.E/B.Tech in Agricultural Information Technology'), ('3', 'B.E/B.Tech in Electrical Engineering'), ('6', 'B.E/B.Tech in Chemical Engineering')], default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('13', 'B.E/B.Tech in Aerospace Engineering'), ('36', 'B.E / B.Tech in Nuclear Engineering'), ('30', 'B.E/B.Tech in Marine Engineering'), ('18', 'B.E/B.Tech in Biotechnology Engineering'), ('17', 'B.E/B.Tech in Production Engineering'), ('8', 'B.E/B.Tech in Instrumentation and Control Engineering'), ('12', 'B.E/B.Tech in Aeronautical Engineering'), ('28', 'B.E/B.Tech in Metallurgy Engineering'), ('34', 'B.E/B.Tech in Polymer Engineering'), ('26', 'B.E/B.Tech in Infrastructure Engineering'), ('14', 'B.E/B.Tech in Automobile Engineering'), ('16', 'B.E/B.Tech in Power Engineering'), ('31', 'B.E/B.Tech in Naval Architecture'), ('20', 'B.E/B.Tech in Plastics Engineering'), ('1', 'B.E/B.Tech in Mechanical Engineering'), ('11', 'B.E/B.Tech in Petroleum Engineering'), ('7', 'B.E/B.Tech in Information Technology'), ('23', 'B.E/B.Tech in Environmental Engineering'), ('32', 'B.E/B.Tech in Geoinformatics'), ('15', 'B.E/B.Tech in Mining Engineering'), ('22', 'B.E/B.Tech in Agricultural Engineering'), ('21', 'B.E/B.Tech in Food Processing and Technology'), ('35', 'B.E/B.Tech in Geotechnical Engineering'), ('10', 'B.E/B.Tech in Electronics and Telecommunication Engineering'), ('4', 'B.E/B.Tech in Electrical and Electronics Engineering'), ('5', 'B.E/B.Tech in Civil Engineering'), ('2', 'B.E/B.Tech in Electronics and Communication Engineering'), ('27', 'B.E/B.Tech in Motorsport Engineering'), ('24', 'B.E/B.Tech in Dairy Technology and Engineering'), ('0', 'B.E/B.Tech in Computer Science Engineering'), ('9', 'B.E/B.Tech in Electronics Engineering'), ('19', 'B.E/B.Tech in Genetic Engineering'), ('33', 'B.E/B.Tech in Petrochemical Engineering'), ('29', 'B.E/B.Tech in Textile Engineering'), ('25', 'B.E/B.Tech in Agricultural Information Technology'), ('3', 'B.E/B.Tech in Electrical Engineering'), ('6', 'B.E/B.Tech in Chemical Engineering')], default='0', max_length=255),
        ),
    ]
