const List<String> degreeList = [
  'B.E/B.Tech in Computer Science Engineering',
  'B.E/B.Tech in Mechanical Engineering',
  'B.E/B.Tech in Electronics and Communication Engineering',
  'B.E/B.Tech in Electrical Engineering',
  'B.E/B.Tech in Electrical and Electronics Engineering',
  'B.E/B.Tech in Civil Engineering',
  'B.E/B.Tech in Chemical Engineering',
  'B.E/B.Tech in Information Technology',
  'B.E/B.Tech in Instrumentation and Control Engineering',
  'B.E/B.Tech in Electronics Engineering',
  'B.E/B.Tech in Electronics and Telecommunication Engineering',
  'B.E/B.Tech in Petroleum Engineering',
  'B.E/B.Tech in Aeronautical Engineering',
  'B.E/B.Tech in Aerospace Engineering',
  'B.E/B.Tech in Automobile Engineering',
  'B.E/B.Tech in Mining Engineering',
  'B.E/B.Tech in Power Engineering',
  'B.E/B.Tech in Production Engineering',
  'B.E/B.Tech in Biotechnology Engineering',
  'B.E/B.Tech in Genetic Engineering',
  'B.E/B.Tech in Plastics Engineering',
  'B.E/B.Tech in Food Processing and Technology',
  'B.E/B.Tech in Agricultural Engineering',
  'B.E/B.Tech in Environmental Engineering',
  'B.E/B.Tech in Dairy Technology and Engineering',
  'B.E/B.Tech in Agricultural Information Technology',
  'B.E/B.Tech in Infrastructure Engineering',
  'B.E/B.Tech in Motorsport Engineering',
  'B.E/B.Tech in Metallurgy Engineering',
  'B.E/B.Tech in Textile Engineering',
  'B.E/B.Tech in Marine Engineering',
  'B.E/B.Tech in Naval Architecture',
  'B.E/B.Tech in Geoinformatics',
  'B.E/B.Tech in Petrochemical Engineering',
  'B.E/B.Tech in Polymer Engineering',
  'B.E/B.Tech in Geotechnical Engineering',
  'B.E / B.Tech in Nuclear Engineering',
];

const List<String> delivery_choices = [
  "Accepted",
  "Transit",
  "Delivered",
  "Failed Attempt",
  "Expired",
  "Waiting",
  "Rejected",
];

constList<String> certificate_choices = [
  "Semester Certificate",
  "Migration Certificate",
  "Domicile Certificate",
  "Affadavit",
  "Character Certificate",
  "Event",
];
