degree_choices = {
    ('0', 'B.E/B.Tech in Computer Science Engineering'),
    ('1', 'B.E/B.Tech in Mechanical Engineering'),
    ('2', 'B.E/B.Tech in Electronics and Communication Engineering'),
    ('3', 'B.E/B.Tech in Electrical Engineering'),
    ('4', 'B.E/B.Tech in Electrical and Electronics Engineering'),
    ('5', 'B.E/B.Tech in Civil Engineering'),
    ('6', 'B.E/B.Tech in Chemical Engineering'),
    ('7', 'B.E/B.Tech in Information Technology'),
    ('8', 'B.E/B.Tech in Instrumentation and Control Engineering'),
    ('9', 'B.E/B.Tech in Electronics Engineering'),
    ('10', 'B.E/B.Tech in Electronics and Telecommunication Engineering'),
    ('11', 'B.E/B.Tech in Petroleum Engineering'),
    ('12', 'B.E/B.Tech in Aeronautical Engineering'),
    ('13', 'B.E/B.Tech in Aerospace Engineering'),
    ('14', 'B.E/B.Tech in Automobile Engineering'),
    ('15', 'B.E/B.Tech in Mining Engineering'),
    ('16', 'B.E/B.Tech in Power Engineering'),
    ('17', 'B.E/B.Tech in Production Engineering'),
    ('18', 'B.E/B.Tech in Biotechnology Engineering'),
    ('19', 'B.E/B.Tech in Genetic Engineering'),
    ('20', 'B.E/B.Tech in Plastics Engineering'),
    ('21', 'B.E/B.Tech in Food Processing and Technology'),
    ('22', 'B.E/B.Tech in Agricultural Engineering'),
    ('23', 'B.E/B.Tech in Environmental Engineering'),
    ('24', 'B.E/B.Tech in Dairy Technology and Engineering'),
    ('25', 'B.E/B.Tech in Agricultural Information Technology'),
    ('26', 'B.E/B.Tech in Infrastructure Engineering'),
    ('27', 'B.E/B.Tech in Motorsport Engineering'),
    ('28', 'B.E/B.Tech in Metallurgy Engineering'),
    ('29', 'B.E/B.Tech in Textile Engineering'),
    ('30', 'B.E/B.Tech in Marine Engineering'),
    ('31', 'B.E/B.Tech in Naval Architecture'),
    ('32', 'B.E/B.Tech in Geoinformatics'),
    ('33', 'B.E/B.Tech in Petrochemical Engineering'),
    ('34', 'B.E/B.Tech in Polymer Engineering'),
    ('35', 'B.E/B.Tech in Geotechnical Engineering'),
    ('36', 'B.E / B.Tech in Nuclear Engineering'),
}
